[metadata]
  name = "app-and-node"
  author = "Bidon15"

[global]
  plan = "celestia-app"
  case = "capp-3"
  total_instances = 6
  builder = "docker:generic"
  runner = "local:docker"
  disable_metrics = false

[[groups]]
  id = "app"
  [groups.resources]
    memory = ""
    cpu = ""
  [groups.instances]
    count = 3
    percentage = 0.0
  [groups.build]
  [groups.run]
    artifact = ""
    [groups.run.test_params]
      role = "app"

[[groups]]
  id = "node"
  [groups.resources]
    memory = ""
    cpu = ""
  [groups.instances]
    count = 3
    percentage = 0.0
  [groups.build]
  [groups.run]
    artifact = ""
    [groups.run.test_params]
      role = "node"
