[metadata]
  name = "app-validator"
  author = "Bidon15"

[global]
  plan = "celestia-app"
  case = "init-val"
  total_instances = 3
  builder = "docker:generic"
  runner = "cluster:k8s"
  disable_metrics = false

[[groups]]
  id = "rov"
  [groups.resources]
    memory = ""
    cpu = ""
  [groups.instances]
    count = 3
    percentage = 0.0
  [groups.build]
  [groups.run]
    artifact = ""
    [groups.run.test_params]
      role = "vals"
