name = "celestia"

[defaults]
builder = "docker:generic"
runner = "local:docker"

[builders."docker:generic"]
enabled = true
build_base_image = "golang:1.18.3"
go_version = "1.18"
enable_go_build_cache = true

[runners."local:docker"]
enabled = true

[runners."cluster:k8s"]
enabled = true

[[testcases]]
name = "init-val"
instances = { min = 1, max = 100, default = 3 }
    [testcases.params]
    validator = { type = "int", default = 3}
    persistent-peers = { type = "int", default = 3}

[[testcases]]
name = "node-sync"
instances = { min = 4, max = 100, default = 12 }
    [testcases.params]
    validator = { type = "int", default = 3}
    persistent-peers = { type = "int", default = 3}
    bridge = { type = "int", default = 3}
    full = { type = "int", default = 3}
    light = { type = "int", default = 3}
