name = "celestia-app"

[defaults]
builder = "exec:go"
runner = "local:exec"

[builders."docker:go"]
enabled = true
go_version = "1.17"
build_base_image = "golang:1.17.8"
enable_go_build_cache = true

[builders."exec:go"]
enabled = true
go_version = "1.17"

[runners."local:docker"]
enabled = true

[runners."local:exec"]
enabled = true

[runners."cluster:swarm"]
enabled = true

[runners."cluster:k8s"]
enabled = true

[[testcases]]
name = "capp-1"
instances = { min = 1, max = 100, default = 1 }

    [testcases.params]
    orc    = { type = "int", default = 1 }
    app1   = { type = "string", default = "/core-configs/.celestia-app-1" }
    app2   = { type = "string", default = "/core-configs/.celestia-app-2" }
    app3   = { type = "string", default = "/core-configs/.celestia-app-3" }
    app4   = { type = "string", default = "/core-configs/.celestia-app-4" }
    app5   = { type = "string", default = "/core-configs/.celestia-app-5" }
    app6   = { type = "string", default = "/core-configs/.celestia-app-6" }
    app7   = { type = "string", default = "/core-configs/.celestia-app-7" }
    app8   = { type = "string", default = "/core-configs/.celestia-app-8" }
    app9   = { type = "string", default = "/core-configs/.celestia-app-9" }
    app10   = { type = "string", default = "/core-configs/.celestia-app-10" }