[metadata]
  name = "003-full-sync-past-3-3-3-3-set"
  author = "Bidon15"

[global]
  plan = "celestia"
  case = "003-full-sync-past"
  total_instances = 12
  builder = "docker:generic"
  runner = "cluster:k8s"
  disable_metrics = false

[global.run.test_params]
  persistent-peers = "3"
  submit-times = "42"
  msg-size = "100000"
  validator = "3"
  bridge = "3"
  full = "3"
  light = "3"

[[groups]]
  id = "validators"
  builder = "docker:generic"
  [groups.resources]
    memory = ""
    cpu = ""
  [groups.instances]
    count = 3
    percentage = 0.0
  [groups.build_config]
    build_base_image = "golang:1.18.3"
    enable_go_build_cache = true
    enabled = true
    go_version = "1.18"
  [groups.build]
  [groups.run]
    [groups.run.test_params]
    latency = "0"
    bandwidth = "256Mib"
    role = "validator"

[[groups]]
  id = "bridges"
  builder = "docker:generic"
  [groups.resources]
    memory = ""
    cpu = ""
  [groups.instances]
    count = 3
    percentage = 0.0
  [groups.build_config]
    build_base_image = "golang:1.18.3"
    enable_go_build_cache = true
    enabled = true
    go_version = "1.18"
  [groups.build]
  [groups.run]
    [groups.run.test_params]
    latency = "0"
    bandwidth = "256Mib"
    block-height = "30"
    role = "bridge"

[[groups]]
  id = "fulls"
  builder = "docker:generic"
  [groups.resources]
    memory = ""
    cpu = ""
  [groups.instances]
    count = 3
    percentage = 0.0
  [groups.build_config]
    build_base_image = "golang:1.18.3"
    enable_go_build_cache = true
    enabled = true
    go_version = "1.18"
  [groups.build]
  [groups.run]
    [groups.run.test_params]
    latency = "0"
    bandwidth = "256Mib"
    block-height = "40"
    role = "full"

[[groups]]
  id = "lights"
  builder = "docker:generic"
  [groups.resources]
    memory = ""
    cpu = ""
  [groups.instances]
    count = 3
    percentage = 0.0
  [groups.build_config]
    build_base_image = "golang:1.18.3"
    enable_go_build_cache = true
    enabled = true
    go_version = "1.18"
  [groups.build]
  [groups.run]
    [groups.run.test_params]
    latency = "0"
    bandwidth = "100Mib"
    block-height = "40"
    role = "light"
