[metadata]
  name = "reconstruction"
  author = "Bidon15"

[global]
  plan = "celestia"
  case = "reconstruction"
  total_instances = 365
  builder = "docker:generic"
  runner = "cluster:k8s"
  disable_metrics = false
  [global.run]
    artifact = ""
    [global.run.test_params]
      bridge = "5"
      execution-time = "20"
      full = "2"
      light = "350"
      msg-size = "6000"
      persistent-peers = "5"
      seed = "5"
      submit-times = "21"
      validator = "5"

[[groups]]
  id = "seeds"
  builder = "docker:generic"
  [groups.resources]
    memory = "4Gi"
    cpu = "3"
  [groups.instances]
    count = 5
    percentage = 0.0
  [groups.build_config]
    build_base_image = "golang:1.19.1"
    enable_go_build_cache = true
    enabled = true
    go_version = "1.19"
  [groups.build]
  [groups.run]
    artifact = ""
    [groups.run.test_params]
      bandwidth = "256Mib"
      latency = "50"
      role = "seed"

[[groups]]
  id = "validators"
  builder = "docker:generic"
  [groups.resources]
    memory = "4Gi"
    cpu = "3000m"
  [groups.instances]
    count = 5
    percentage = 0.0
  [groups.build_config]
    build_base_image = "golang:1.19.1"
    enable_go_build_cache = true
    enabled = true
    go_version = "1.19"
  [groups.build]
  [groups.run]
    artifact = ""
    [groups.run.test_params]
      bandwidth = "256Mib"
      latency = "50"
      role = "validator"

[[groups]]
  id = "bridges"
  builder = "docker:generic"
  [groups.resources]
    memory = "4Gi"
    cpu = "3000m"
  [groups.instances]
    count = 5
    percentage = 0.0
  [groups.build_config]
    build_base_image = "golang:1.19.1"
    enable_go_build_cache = true
    enabled = true
    go_version = "1.19"
  [groups.build]
  [groups.run]
    artifact = ""
    [groups.run.test_params]
      bandwidth = "256Mib"
      block-height = "5"
      latency = "50"
      role = "bridge"

[[groups]]
  id = "fulls"
  builder = "docker:generic"
 [groups.resources]
    memory = "8Gi"
    cpu = "8000m"
  [groups.instances]
    count = 2
    percentage = 0.0
  [groups.build_config]
    build_base_image = "golang:1.19.1"
    enable_go_build_cache = true
    enabled = true
    go_version = "1.19"
  [groups.build]
  [groups.run]
    artifact = ""
    [groups.run.test_params]
      bandwidth = "256Mib"
      block-height = "5"
      latency = "50"
      role = "full"

[[groups]]
  id = "lights"
  builder = "docker:generic"
  [groups.resources]
    memory = "1Gi"
    cpu = "300m"
  [groups.instances]
    count = 350
    percentage = 0.0
  [groups.build_config]
    build_base_image = "golang:1.19.1"
    enable_go_build_cache = true
    enabled = true
    go_version = "1.19"
  [groups.build]
  [groups.run]
    artifact = ""
    [groups.run.test_params]
      bandwidth = "256Mib"
      block-height = "5"
      latency = "50"
      role = "light"
