[metadata]
  name = "das-benchmarks"
  author = "derrandz"

[global]
  plan = "celestia"
  case = "001-lights-dasing-latest-from-bridges"
  total_instances = 282
  builder = "docker:generic"
  runner = "cluster:k8s"
  disable_metrics = false

# we define 1 validator that produces 8mb blocks
# the msg-size does not result in exactly 8mb
# because we are accounting for padding
[global.run.test_params]
  execution-time = "10"
  persistent-peers = "1"
  submit-times = "10"
  msg-size = "700000"
  validator = "1"
  bridge = "1"
  light = "280"
  block-height = "30"
  otel-collector-address = "178.128.163.171:4318"

[[groups]]
  id = "validators"
  builder = "docker:generic"
  [groups.resources]
    memory = "4Gi"
    cpu = "1"
  [groups.instances]
    count = 1
    percentage = 0.0
  [groups.build_config]
    build_base_image = "golang:1.19.1"
    enable_go_build_cache = true
    enabled = true
    go_version = "1.19"
  [groups.build]
  [groups.run]
    [groups.run.test_params]
    latency = "50"
    bandwidth = "256Mib"
    role = "validator"

[[groups]]
  id = "bridges"
  builder = "docker:generic"
  [groups.resources]
    memory = "1Gi"
    cpu = "1"
  [groups.instances]
    count = 1
    percentage = 0.0
  [groups.build_config]
    build_base_image = "golang:1.19.1"
    enable_go_build_cache = true
    enabled = true
    go_version = "1.19"
  [groups.build]
  [groups.run]
    [groups.run.test_params]
    latency = "50"
    bandwidth = "256Mib"
    role = "bridge"

[[groups]]
  id = "lights"
  builder = "docker:generic"
  [groups.resources]
    memory = "512Mi"
    cpu = "500m"
  [groups.instances]
    count = 280
    percentage = 0.0
  [groups.build_config]
    build_base_image = "golang:1.19.1"
    enable_go_build_cache = true
    enabled = true
    go_version = "1.19"
  [groups.build]
  [groups.run]
    [groups.run.test_params]
    latency = "50"
    bandwidth = "256Mib"
    role = "light"
