[metadata]
  name = "001-val-large-txs-40-set"
  author = "Bidon15"

[global]
  plan = "001-big-blocks"
  case = "001-val-large-txs"
  total_instances = 40
  builder = "docker:generic"
  runner = "cluster:k8s"
  disable_metrics = false

[global.run.test_params]
  execution-time = "10"
  latency = "200"
  bandwidth = "320Mib"
  validator = "40"
  persistent-peers = "10"
  submit-times = "10"
  msg-size = "100000"

[[groups]]
  id = "validators"
  builder = "docker:generic"
  [groups.resources]
    memory = "4Gi"
    cpu = "3"
  [groups.instances]
    count = 40
    percentage = 0.0
  [groups.build_config]
    build_base_image = "golang:1.19.1"
    enable_go_build_cache = true
    enabled = true
    go_version = "1.19"
  [groups.build]
  [groups.run]
    artifact = ""
