[metadata]
  name = "app-and-node"
  author = "Bidon15"

[global]
  plan = "celestia"
  case = "node-sync"
  total_instances = 12
  builder = "docker:generic"
  runner = "local:docker"
  disable_metrics = false

[[groups]]
  id = "app"
  builder = "docker:generic"
  [groups.resources]
    memory = ""
    cpu = ""
  [groups.instances]
    count = 3
    percentage = 0.0
  [groups.build_config]
    build_base_image = "golang:1.18.3"
    enable_go_build_cache = true
    enabled = true
    go_version = "1.18"
  [groups.build]
  [groups.run]
    artifact = ""

[[groups]]
  id = "bridge"
  builder = "docker:generic"
  [groups.resources]
    memory = ""
    cpu = ""
  [groups.instances]
    count = 3
    percentage = 0.0
  [groups.build_config]
    build_base_image = "golang:1.18.3"
    enable_go_build_cache = true
    enabled = true
    go_version = "1.18"
  [groups.build]
  [groups.run]
    artifact = ""

[[groups]]
  id = "full"
  builder = "docker:generic"
  [groups.resources]
    memory = ""
    cpu = ""
  [groups.instances]
    count = 3
    percentage = 0.0
  [groups.build_config]
    build_base_image = "golang:1.18.3"
    enable_go_build_cache = true
    enabled = true
    go_version = "1.18"
  [groups.build]
  [groups.run]
    artifact = ""

[[groups]]
  id = "light"
  builder = "docker:generic"
  [groups.resources]
    memory = ""
    cpu = ""
  [groups.instances]
    count = 3
    percentage = 0.0
  [groups.build_config]
    build_base_image = "golang:1.18.3"
    enable_go_build_cache = true
    enabled = true
    go_version = "1.18"
  [groups.build]
  [groups.run]
    artifact = ""
