[metadata]
  name = "004-full-light-past-100-100-50-1000-set"
  author = "Bidon15"

[global]
  plan = "celestia"
  case = "004-full-light-past"
  total_instances = 2255
  builder = "docker:generic"
  runner = "cluster:k8s"
  disable_metrics = false
  [global.run]
    artifact = ""
    [global.run.test_params]
      bridge = "100"
      execution-time = "40"
      full = "50"
      light = "1000"
      msg-size = "64000"
      persistent-peers = "10"
      seed = "5"
      submit-times = "102"
      validator = "100"

[[groups]]
  id = "seeds"
  builder = "docker:generic"
  [groups.resources]
    memory = "4Gi"
    cpu = "3"
  [groups.instances]
    count = 5
    percentage = 0.0
  [groups.build_config]
    build_base_image = "golang:1.19.1"
    enable_go_build_cache = true
    enabled = true
    go_version = "1.19"
  [groups.build]
  [groups.run]
    artifact = ""
    [groups.run.test_params]
      bandwidth = "320Mib"
      latency = "100"
      role = "seed"

[[groups]]
  id = "validators"
  builder = "docker:generic"
  [groups.resources]
    memory = "4Gi"
    cpu = "3"
  [groups.instances]
    count = 100
    percentage = 0.0
  [groups.build_config]
    build_base_image = "golang:1.19.1"
    enable_go_build_cache = true
    enabled = true
    go_version = "1.19"
  [groups.build]
  [groups.run]
    artifact = ""
    [groups.run.test_params]
      bandwidth = "320Mib"
      latency = "100"
      role = "validator"

[[groups]]
  id = "bridges"
  builder = "docker:generic"
  [groups.resources]
    memory = "4Gi"
    cpu = "3"
  [groups.instances]
    count = 100
    percentage = 0.0
  [groups.build_config]
    build_base_image = "golang:1.19.1"
    enable_go_build_cache = true
    enabled = true
    go_version = "1.19"
  [groups.build]
  [groups.run]
    artifact = ""
    [groups.run.test_params]
      bandwidth = "320Mib"
      block-height = "50"
      latency = "100"
      role = "bridge"

[[groups]]
  id = "fulls"
  builder = "docker:generic"
  [groups.resources]
    memory = "4Gi"
    cpu = "3"
  [groups.instances]
    count = 50
    percentage = 0.0
  [groups.build_config]
    build_base_image = "golang:1.19.1"
    enable_go_build_cache = true
    enabled = true
    go_version = "1.19"
  [groups.build]
  [groups.run]
    artifact = ""
    [groups.run.test_params]
      bandwidth = "320Mib"
      block-height = "100"
      latency = "100"
      role = "full"

[[groups]]
  id = "lights"
  builder = "docker:generic"
  [groups.resources]
    memory = "300Mi"
    cpu = "1"
  [groups.instances]
    count = 1000
    percentage = 0.0
  [groups.build_config]
    build_base_image = "golang:1.19.1"
    enable_go_build_cache = true
    enabled = true
    go_version = "1.19"
  [groups.build]
  [groups.run]
    artifact = ""
    [groups.run.test_params]
      bandwidth = "100Mib"
      block-height = "100"
      latency = "100"
      role = "light"
