[metadata]
  name = "app-and-node"
  author = "Bidon15"

[global]
  plan = "celestia"
  case = "node-sync"
  total_instances = 12
  builder = "docker:generic"
  runner = "cluster:k8s"
  disable_metrics = false

[global.run.test_params]
  validator = "3"
  bridge = "3"
  full = "3"
  light = "3"

[[groups]]
  id = "instance"
  builder = "docker:generic"
  [groups.resources]
    memory = "4Gi"
    cpu = "3"
  [groups.instances]
    count = 12
    percentage = 0.0
  [groups.build_config]
    build_base_image = "golang:1.18.3"
    enable_go_build_cache = true
    enabled = true
    go_version = "1.18"
  [groups.build]
  [groups.run]
    artifact = ""
