[metadata]
  name = "006-light-das-latest-1-20-set"
  author = "derrandz"

[global]
  plan = "celestia"
  case = "006-light-das-latest"
  total_instances = 12
  builder = "docker:generic"
  runner = "local:docker"
  disable_metrics = false

[global.run.test_params]
  execution-time = "30"
  persistent-peers = "3"
#  submit-times = "42"
  msg-size = "100000"
  full = "1"
# or bridge = "1"
  light = "20"

# [[groups]]
#  id = "bridges"
#  builder = "docker:generic"
#  [groups.resources]
#    memory = ""
#    cpu = ""
#  [groups.instances]
#    count = 1
#    percentage = 0.0
#  [groups.build_config]
#    build_base_image = "golang:1.19.1"
#    enable_go_build_cache = true
#    enabled = true
#    go_version = "1.19"
#  [groups.build]
#  [groups.run]
#   [groups.run.test_params]
#   latency = "0"
#   bandwidth = "256Mib"
#   block-height = "1"
#   role = "bridge"

[[groups]]
  id = "fulls"
  builder = "docker:generic"
  [groups.resources]
    memory = ""
    cpu = ""
  [groups.instances]
    count = 1
    percentage = 0.0
  [groups.build_config]
    build_base_image = "golang:1.19.1"
    enable_go_build_cache = true
    enabled = true
    go_version = "1.19"
  [groups.build]
  [groups.run]
    [groups.run.test_params]
    latency = "0"
    bandwidth = "256Mib"
    block-height = "40"
    role = "full"

[[groups]]
  id = "lights"
  builder = "docker:generic"
  [groups.resources]
    memory = ""
    cpu = ""
  [groups.instances]
    count = 20
    percentage = 0.0
  [groups.build_config]
    build_base_image = "golang:1.19.1"
    enable_go_build_cache = true
    enabled = true
    go_version = "1.19"
  [groups.build]
  [groups.run]
    [groups.run.test_params]
    latency = "0"
    bandwidth = "100Mib"
    block-height = "40"
    role = "light"
