[metadata]
  name = "tc-002-da-sync-40-40-20-100-set"
  author = "Bidon15"

[global]
  plan = "celestia"
  case = "tc-002-da-sync"
  total_instances = 200
  builder = "docker:generic"
  runner = "cluster:k8s"
  disable_metrics = false

[global.run.test_params]
  persistent-peers = "10"
  submit-times = "10"
  msg-size = "100000"
  validator = "40"
  bridge = "40"
  full = "20"
  light = "100"

[[groups]]
  id = "validators"
  builder = "docker:generic"
  [groups.resources]
    memory = "4Gi"
    cpu = "3"
  [groups.instances]
    count = 40
    percentage = 0.0
  [groups.build_config]
    build_base_image = "golang:1.18.3"
    enable_go_build_cache = true
    enabled = true
    go_version = "1.18"
  [groups.build]
  [groups.run]
    [groups.run.test_params]
    latency = "0"
    bandwidth = "256Mib"
    role = "validator"

[[groups]]
  id = "bridges"
  builder = "docker:generic"
  [groups.resources]
    memory = "4Gi"
    cpu = "3"
  [groups.instances]
    count = 40
    percentage = 0.0
  [groups.build_config]
    build_base_image = "golang:1.18.3"
    enable_go_build_cache = true
    enabled = true
    go_version = "1.18"
  [groups.build]
  [groups.run]
    [groups.run.test_params]
    latency = "0"
    bandwidth = "256Mib"
    block-height = "13"
    role = "bridge"

[[groups]]
  id = "fulls"
  builder = "docker:generic"
  [groups.resources]
    memory = "4Gi"
    cpu = "3"
  [groups.instances]
    count = 20
    percentage = 0.0
  [groups.build_config]
    build_base_image = "golang:1.18.3"
    enable_go_build_cache = true
    enabled = true
    go_version = "1.18"
  [groups.build]
  [groups.run]
    [groups.run.test_params]
    latency = "0"
    bandwidth = "256Mib"
    block-height = "12"
    role = "full"

[[groups]]
  id = "lights"
  builder = "docker:generic"
  [groups.resources]
    memory = "4Gi"
    cpu = "2"
  [groups.instances]
    count = 100
    percentage = 0.0
  [groups.build_config]
    build_base_image = "golang:1.18.3"
    enable_go_build_cache = true
    enabled = true
    go_version = "1.18"
  [groups.build]
  [groups.run]
    [groups.run.test_params]
    latency = "0"
    bandwidth = "100Mib"
    block-height = "12"
    role = "light"